version: build{build}

environment:
  SlantVersion: 0.9.1
  SlantPackageVersion: "0.9.1-ci$(APPVEYOR_BUILD_NUMBER)"
  
cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: "$(SlantVersion)"
  assembly_file_version: "$(SlantVersion)"
  assembly_informational_version: "$(SlantPackageVersion)"

nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Debug

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore

build:
  project: Slant.sln
  verbosity: normal

test:
  assemblies:
  - Slant.Tests.dll

artifacts:
 - path: src\Slant\bin\Release\Slant.dll